# Generated by Django 4.0.2 on 2022-02-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name ', max_length=255)),
                ('sku', models.CharField(help_text='Product SKU', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Product description')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
