# Generated by Django 4.0.2 on 2022-02-20 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_processedfilehistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id']},
        ),
    ]
