# Generated by Django 4.0.2 on 2022-02-20 07:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebHook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(blank=True, help_text='WebHook URL', validators=[django.core.validators.URLValidator()])),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
